import './globals.css'

// export const metadata = {
//   title: 'MyApp',
//   description: 'Generated by create next app',
//   robots: "nofollow,noindex"
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
